# Generated by Django 5.2.8 on 2025-11-12 04:18

import django.db.models.deletion
import tipo_solicitudes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposolicitud',
            name='responsable',
            field=models.CharField(choices=[('1', 'Control escolar'), ('2', 'Responsable de programa'), ('3', 'Responsable de tutorías'), ('4', 'Director')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FormularioSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario', to='tipo_solicitudes.tiposolicitud')),
            ],
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('etiqueta', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('text', 'Texto corto'), ('textarea', 'Texto largo'), ('number', 'Número'), ('date', 'Fecha'), ('select', 'Selección'), ('file', 'Archivo')], max_length=20)),
                ('requerido', models.BooleanField(default=True)),
                ('opciones', models.TextField(blank=True, help_text="Usar comas para separar opciones (solo para tipo 'select')")),
                ('cantidad_archivos', models.PositiveIntegerField(default=1, help_text='Aplica si el campo es tipo archivo')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='tipo_solicitudes.formulariosolicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_solicitudes.tiposolicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estatus', models.CharField(choices=[('1', 'Creada'), ('2', 'En proceso'), ('3', 'Terminada'), ('4', 'Cancelada')], max_length=1)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='tipo_solicitudes.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_solicitudes.campoformulario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='tipo_solicitudes.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=tipo_solicitudes.models.upload_path)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='tipo_solicitudes.respuestacampo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='tipo_solicitudes.solicitud')),
            ],
        ),
    ]
